services:
  - type: web
    name: lab02-dessolnub
    runtime: php
    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    env: php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      # Agrega otras variables necesarias